<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Operator;
use App\Models\Barang;
use App\Models\Pelanggan;
use Illuminate\Support\Facades\Hash;

class DummyDataSeeder extends Seeder
{
    public function run(): void
    {
        // Operator dummy
        Operator::create([
            'id_operator' => 'OP001',
            'nama_lengkap' => 'Admin Kasir',
            'username' => 'admin',
            'password_hash' => Hash::make('password123'),
            'level_akses' => 'kasir',
            'status_aktif' => true,
        ]);

        // Barang dummy
        $barangData = [
            [
                'kode_barang' => 'BRG001',
                'barcode' => '899999901001',
                'nama_barang' => 'Aqua Botol 600ml',
                'kategori' => 'Minuman',
                'satuan' => 'pcs',
                'stok_sekarang' => 150,
                'harga_jual_normal' => 4000,
                'harga_beli_terakhir' => 2800,
                'status_aktif' => true,
            ],
            [
                'kode_barang' => 'BRG002',
                'barcode' => '899999901002',
                'nama_barang' => 'Indomie Goreng',
                'kategori' => 'Makanan',
                'satuan' => 'pcs',
                'stok_sekarang' => 240,
                'harga_jual_normal' => 3000,
                'harga_beli_terakhir' => 2100,
                'status_aktif' => true,
            ],
            [
                'kode_barang' => 'BRG003',
                'barcode' => '899999901003',
                'nama_barang' => 'Pulpen Pilot Balliner',
                'kategori' => 'Alat Tulis',
                'satuan' => 'pcs',
                'stok_sekarang' => 120,
                'harga_jual_normal' => 3500,
                'harga_beli_terakhir' => 2200,
                'status_aktif' => true,
            ],
            [
                'kode_barang' => 'BRG004',
                'barcode' => '899999901004',
                'nama_barang' => 'Roti Tawar Sari Roti',
                'kategori' => 'Makanan',
                'satuan' => 'pack',
                'stok_sekarang' => 45,
                'harga_jual_normal' => 16000,
                'harga_beli_terakhir' => 12000,
                'status_aktif' => true,
            ],
            [
                'kode_barang' => 'BRG005',
                'barcode' => '899999901005',
                'nama_barang' => 'Sabun Mandi Lifebuoy 100gr',
                'kategori' => 'Kebutuhan Mandi',
                'satuan' => 'pcs',
                'stok_sekarang' => 85,
                'harga_jual_normal' => 6000,
                'harga_beli_terakhir' => 4200,
                'status_aktif' => true,
            ],
            [
                'kode_barang' => 'BRG006',
                'barcode' => '899999901006',
                'nama_barang' => 'Teh Botol Sosro 500ml',
                'kategori' => 'Minuman',
                'satuan' => 'pcs',
                'stok_sekarang' => 95,
                'harga_jual_normal' => 5500,
                'harga_beli_terakhir' => 3800,
                'status_aktif' => true,
            ],
            [
                'kode_barang' => 'BRG007',
                'barcode' => '899999901007',
                'nama_barang' => 'Mie Sedap Goreng',
                'kategori' => 'Makanan',
                'satuan' => 'pcs',
                'stok_sekarang' => 180,
                'harga_jual_normal' => 2800,
                'harga_beli_terakhir' => 1900,
                'status_aktif' => true,
            ],
            [
                'kode_barang' => 'BRG008',
                'barcode' => '899999901008',
                'nama_barang' => 'Buku Tulis Sidu 38 Lembar',
                'kategori' => 'Alat Tulis',
                'satuan' => 'pcs',
                'stok_sekarang' => 200,
                'harga_jual_normal' => 4500,
                'harga_beli_terakhir' => 3200,
                'status_aktif' => true,
            ],
            [
                'kode_barang' => 'BRG009',
                'barcode' => '899999901009',
                'nama_barang' => 'Shampoo Clear Men 180ml',
                'kategori' => 'Kebutuhan Mandi',
                'satuan' => 'pcs',
                'stok_sekarang' => 60,
                'harga_jual_normal' => 18500,
                'harga_beli_terakhir' => 13500,
                'status_aktif' => true,
            ],
            [
                'kode_barang' => 'BRG010',
                'barcode' => '899999901010',
                'nama_barang' => 'Tissue Paseo 200 Sheet',
                'kategori' => 'Kebutuhan Rumah Tangga',
                'satuan' => 'pcs',
                'stok_sekarang' => 75,
                'harga_jual_normal' => 9500,
                'harga_beli_terakhir' => 6800,
                'status_aktif' => true,
            ],
            [
                'kode_barang' => 'BRG011',
                'barcode' => '899999901011',
                'nama_barang' => 'Kopi Kapal Api Special 25gr',
                'kategori' => 'Minuman',
                'satuan' => 'pcs',
                'stok_sekarang' => 300,
                'harga_jual_normal' => 1500,
                'harga_beli_terakhir' => 1000,
                'status_aktif' => true,
            ],
            [
                'kode_barang' => 'BRG012',
                'barcode' => '899999901012',
                'nama_barang' => 'Biskuit Roma Kelapa 160gr',
                'kategori' => 'Makanan',
                'satuan' => 'box',
                'stok_sekarang' => 35,
                'harga_jual_normal' => 12500,
                'harga_beli_terakhir' => 9000,
                'status_aktif' => true,
            ],
            [
                'kode_barang' => 'BRG013',
                'barcode' => '899999901013',
                'nama_barang' => 'Penggaris Plastik 30cm',
                'kategori' => 'Alat Tulis',
                'satuan' => 'pcs',
                'stok_sekarang' => 90,
                'harga_jual_normal' => 2500,
                'harga_beli_terakhir' => 1500,
                'status_aktif' => true,
            ],
            [
                'kode_barang' => 'BRG014',
                'barcode' => '899999901014',
                'nama_barang' => 'Sikat Gigi Formula',
                'kategori' => 'Kesehatan',
                'satuan' => 'pcs',
                'stok_sekarang' => 110,
                'harga_jual_normal' => 5000,
                'harga_beli_terakhir' => 3500,
                'status_aktif' => true,
            ],
            [
                'kode_barang' => 'BRG015',
                'barcode' => '899999901015',
                'nama_barang' => 'Gula Pasir Gulaku 1kg',
                'kategori' => 'Sembako',
                'satuan' => 'kg',
                'stok_sekarang' => 55,
                'harga_jual_normal' => 16500,
                'harga_beli_terakhir' => 12500,
                'status_aktif' => true,
            ],
            [
                'kode_barang' => 'BRG016',
                'barcode' => '899999901016',
                'nama_barang' => 'Minyak Goreng Bimoli 2L',
                'kategori' => 'Sembako',
                'satuan' => 'liter',
                'stok_sekarang' => 40,
                'harga_jual_normal' => 32000,
                'harga_beli_terakhir' => 25000,
                'status_aktif' => true,
            ],
            [
                'kode_barang' => 'BRG017',
                'barcode' => '899999901017',
                'nama_barang' => 'Susu Ultra Milk 250ml',
                'kategori' => 'Minuman',
                'satuan' => 'pcs',
                'stok_sekarang' => 80,
                'harga_jual_normal' => 6500,
                'harga_beli_terakhir' => 4800,
                'status_aktif' => true,
            ],
            [
                'kode_barang' => 'BRG018',
                'barcode' => '899999901018',
                'nama_barang' => 'Sarden ABC 155gr',
                'kategori' => 'Makanan',
                'satuan' => 'pcs',
                'stok_sekarang' => 65,
                'harga_jual_normal' => 9500,
                'harga_beli_terakhir' => 7000,
                'status_aktif' => true,
            ],
            [
                'kode_barang' => 'BRG019',
                'barcode' => '899999901019',
                'nama_barang' => 'Baterai ABC AA 2pcs',
                'kategori' => 'Elektronik',
                'satuan' => 'pcs',
                'stok_sekarang' => 120,
                'harga_jual_normal' => 12000,
                'harga_beli_terakhir' => 8500,
                'status_aktif' => true,
            ],
            [
                'kode_barang' => 'BRG020',
                'barcode' => '899999901020',
                'nama_barang' => 'Kecap Bango 135ml',
                'kategori' => 'Bumbu',
                'satuan' => 'pcs',
                'stok_sekarang' => 95,
                'harga_jual_normal' => 8500,
                'harga_beli_terakhir' => 6000,
                'status_aktif' => true,
            ],
            [
                'kode_barang' => 'BRG021',
                'barcode' => '899999901021',
                'nama_barang' => 'Pensil 2B Faber-Castell',
                'kategori' => 'Alat Tulis',
                'satuan' => 'pcs',
                'stok_sekarang' => 150,
                'harga_jual_normal' => 3000,
                'harga_beli_terakhir' => 1800,
                'status_aktif' => true,
            ],
            [
                'kode_barang' => 'BRG022',
                'barcode' => '899999901022',
                'nama_barang' => 'Penghapus Faber-Castell',
                'kategori' => 'Alat Tulis',
                'satuan' => 'pcs',
                'stok_sekarang' => 130,
                'harga_jual_normal' => 2500,
                'harga_beli_terakhir' => 1500,
                'status_aktif' => true,
            ],
            [
                'kode_barang' => 'BRG023',
                'barcode' => '899999901023',
                'nama_barang' => 'Pewangi Ruangan Stella 225ml',
                'kategori' => 'Kebutuhan Rumah Tangga',
                'satuan' => 'pcs',
                'stok_sekarang' => 45,
                'harga_jual_normal' => 18000,
                'harga_beli_terakhir' => 13000,
                'status_aktif' => true,
            ],
            [
                'kode_barang' => 'BRG024',
                'barcode' => '899999901024',
                'nama_barang' => 'Sabun Cuci Piring Sunlight 450ml',
                'kategori' => 'Kebutuhan Rumah Tangga',
                'satuan' => 'pcs',
                'stok_sekarang' => 70,
                'harga_jual_normal' => 12500,
                'harga_beli_terakhir' => 9000,
                'status_aktif' => true,
            ],
            [
                'kode_barang' => 'BRG025',
                'barcode' => '899999901025',
                'nama_barang' => 'Ciki Chitato 65gr',
                'kategori' => 'Snack',
                'satuan' => 'pcs',
                'stok_sekarang' => 200,
                'harga_jual_normal' => 8500,
                'harga_beli_terakhir' => 6000,
                'status_aktif' => true,
            ],
        ];

        foreach ($barangData as $barang) {
            Barang::create($barang);
        }

        // Pelanggan dummy
        Pelanggan::create([
            'kode_pelanggan' => 'CUST001',
            'nama_pelanggan' => 'Pelanggan Umum',
            'tipe_pelanggan' => 'retail',
            'status_aktif' => true,
        ]);

        $this->command->info('Data dummy berhasil ditambahkan!');
        $this->command->info('Login dengan:');
        $this->command->info('Username: admin');
        $this->command->info('Password: password123');
    }
}
